### ISSUE TITLE
老铁，这么好的库，为啥Pod的安装不了啊，SnapKit版本怎么限定到4.2了

### ISSUE THREAD

**Issue by Whereeee** [xaoxuu/ProHUD#3]
[!] CocoaPods could not find compatible versions for pod "SnapKit":
  In snapshot (Podfile.lock):
    SnapKit (= 5.6.0, ~> 5.6.0)

  In Podfile:
    ProHUD was resolved to 1.0, which depends on
      SnapKit (= 4.2.0)

    SnapKit (~> 5.6.0)

安装报错

**Comment by xaoxuu** [comment]
由于用户量太少了，同时支持多个平台维护成本比较高，所以从 `3.x` 开始不再支持 CocoaPods 方式安装了。
ProHUD 从 `3.x` 起依赖的 SnapKit 版本升级到了 `5.x`，支持 Swift Package 方式安装，如果项目无法使用 Swift Package 或依赖存在冲突，可以尝试通过直接引用源码方式使用。🥹
