### ISSUE TITLE
兄弟啊  demo打不开啊，说是用未来的xcode创建的

### ISSUE THREAD

**Issue by WilliamChengJM** [xaoxuu/ProHUD#4]
<img width="260" alt="image" src="https://github.com/xaoxuu/ProHUD/assets/141697729/537ddce5-9fe2-4f79-8b61-495424eea294">
是不是用beta版本创建的 试着将objcVersion改为50，项目能打开了，但是找不到Prohud库，去spm中下载，点击package depenencies xcode直接崩溃

**Comment by xaoxuu** [comment]
请更新到最新的Xcode版本试一下。
